"""Detail analysis for parking_2 C-class precision failures.

This offline tool reads geometry CSVs generated by
analyze_scene_parking2_failure.py and further decomposes
Outdoor_Day_penno_parking_2 C_coarse_success_precise_fail samples into
center/size/volume-related subtypes. It does not load models, checkpoints, or
GPU resources.

Example:
    python tools/analyze_parking2_c_failure_detail.py
"""

import argparse
import csv
import math
from collections import Counter, defaultdict
from pathlib import Path


DEFAULT_PARKING2_CSV = "outputs/scene_parking2_analysis/parking2_error_geometry.csv"
DEFAULT_PLAZA_CSV = "outputs/scene_parking2_analysis/plaza_error_geometry.csv"
DEFAULT_OUT_DIR = "outputs/scene_parking2_c_detail_analysis"
C_LABEL = "C_coarse_success_precise_fail"
E_LABEL = "E_strict_success"
EPS = 1e-9

QUANTILE_METRICS = (
    "top1_iou",
    "best_top10_iou",
    "top1_center_error",
    "top1_size_l1_error",
    "top1_volume_ratio",
    "gt_volume",
    "gt_center_distance",
    "top1_to_best_top10_iou_gap",
)

QUANTILE_COLUMNS = (
    "scene",
    "primary_label",
    "metric",
    "mean",
    "p10",
    "p25",
    "p50",
    "p75",
    "p90",
    "num_records",
)

SUBTYPE_COLUMNS = (
    "id",
    "scene",
    "frame_id",
    "utterance",
    "top1_iou",
    "best_top10_iou",
    "best_top10_rank",
    "top1_to_best_top10_iou_gap",
    "gt_center_x",
    "gt_center_y",
    "gt_center_z",
    "gt_size_x",
    "gt_size_y",
    "gt_size_z",
    "gt_volume",
    "gt_center_distance",
    "gt_diag",
    "gt_size_sum",
    "top1_center_x",
    "top1_center_y",
    "top1_center_z",
    "top1_size_x",
    "top1_size_y",
    "top1_size_z",
    "top1_volume",
    "top1_center_error",
    "center_error_norm",
    "top1_size_l1_error",
    "size_l1_error_norm",
    "top1_volume_ratio",
    "size_x_abs_error",
    "size_y_abs_error",
    "size_z_abs_error",
    "size_x_rel_error",
    "size_y_rel_error",
    "size_z_rel_error",
    "center_good_fixed",
    "size_good_fixed",
    "volume_good_fixed",
    "center_good_ebased",
    "size_good_ebased",
    "volume_good_ebased",
    "near_success",
    "low_c",
    "center_lt_05_iou_lt_05",
    "high_size_x_error",
    "high_size_y_error",
    "high_size_z_error",
    "c_subtype",
    "subtype_explanation",
    "json_path",
)

SUBTYPE_SUMMARY_COLUMNS = (
    "c_subtype",
    "count",
    "ratio",
    "mean_top1_iou",
    "median_top1_iou",
    "mean_best_top10_iou",
    "mean_top1_center_error",
    "median_top1_center_error",
    "mean_center_error_norm",
    "median_center_error_norm",
    "mean_top1_size_l1_error",
    "median_top1_size_l1_error",
    "mean_size_l1_error_norm",
    "median_size_l1_error_norm",
    "mean_top1_volume_ratio",
    "median_top1_volume_ratio",
    "mean_top1_to_best_top10_iou_gap",
)

AXIS_COLUMNS = (
    "axis",
    "mean_abs_error",
    "median_abs_error",
    "mean_rel_error",
    "median_rel_error",
    "ratio_rel_error_gt_0.1",
    "ratio_rel_error_gt_0.2",
    "ratio_rel_error_gt_0.3",
)


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze parking_2 C-class precision failures offline.")
    parser.add_argument("--parking2_csv", default=DEFAULT_PARKING2_CSV)
    parser.add_argument("--plaza_csv", default=DEFAULT_PLAZA_CSV)
    parser.add_argument("--out_dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--center_good_abs_threshold", type=float, default=0.5)
    parser.add_argument("--size_good_norm_threshold", type=float, default=0.10)
    parser.add_argument("--volume_ratio_low", type=float, default=0.8)
    parser.add_argument("--volume_ratio_high", type=float, default=1.2)
    parser.add_argument("--near_success_iou", type=float, default=0.45)
    parser.add_argument("--low_c_iou_high", type=float, default=0.30)
    return parser.parse_args()


def safe_float(value, default=math.nan):
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return float(value)
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if math.isfinite(number) else default


def is_finite(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


def finite_values(values):
    return [value for value in values if is_finite(value)]


def mean(values):
    values = finite_values(values)
    return sum(values) / len(values) if values else math.nan


def median(values):
    return quantile(values, 0.5)


def quantile(values, q):
    values = sorted(finite_values(values))
    if not values:
        return math.nan
    if len(values) == 1:
        return values[0]
    pos = (len(values) - 1) * q
    low = int(math.floor(pos))
    high = int(math.ceil(pos))
    if low == high:
        return values[low]
    weight = pos - low
    return values[low] * (1.0 - weight) + values[high] * weight


def ratio(count, denom):
    return float(count) / float(denom) if denom else math.nan


def safe_div(numer, denom):
    if not is_finite(numer) or not is_finite(denom) or abs(denom) <= EPS:
        return math.nan
    return numer / denom


def safe_l2(values):
    if not all(is_finite(value) for value in values):
        return math.nan
    return math.sqrt(sum(value * value for value in values))


def read_csv(path):
    with Path(path).open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path, rows, fieldnames):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def scene_name(rows, fallback):
    for row in rows:
        if row.get("scene"):
            return row["scene"]
    return fallback


def add_numeric_fields(row):
    result = dict(row)
    numeric_keys = set(QUANTILE_METRICS) | {
        "gt_center_x",
        "gt_center_y",
        "gt_center_z",
        "gt_size_x",
        "gt_size_y",
        "gt_size_z",
        "top1_center_x",
        "top1_center_y",
        "top1_center_z",
        "top1_size_x",
        "top1_size_y",
        "top1_size_z",
        "best_top10_rank",
        "gt_volume",
        "gt_center_distance",
        "top1_volume",
    }
    for key in numeric_keys:
        result[key] = safe_float(result.get(key))
    return result


def normalized_error_fields(row):
    gt_sizes = [row.get("gt_size_x"), row.get("gt_size_y"), row.get("gt_size_z")]
    top1_sizes = [row.get("top1_size_x"), row.get("top1_size_y"), row.get("top1_size_z")]
    gt_diag = safe_l2(gt_sizes)
    gt_size_sum = sum(gt_sizes) if all(is_finite(value) for value in gt_sizes) else math.nan
    size_abs = []
    size_rel = []
    for pred, gt in zip(top1_sizes, gt_sizes):
        abs_err = abs(pred - gt) if is_finite(pred) and is_finite(gt) else math.nan
        size_abs.append(abs_err)
        size_rel.append(safe_div(abs_err, gt))
    return {
        "gt_diag": gt_diag,
        "gt_size_sum": gt_size_sum,
        "center_error_norm": safe_div(row.get("top1_center_error"), gt_diag),
        "size_l1_error_norm": safe_div(row.get("top1_size_l1_error"), gt_size_sum),
        "size_x_abs_error": size_abs[0],
        "size_y_abs_error": size_abs[1],
        "size_z_abs_error": size_abs[2],
        "size_x_rel_error": size_rel[0],
        "size_y_rel_error": size_rel[1],
        "size_z_rel_error": size_rel[2],
    }


def quantile_rows(groups):
    rows = []
    for (scene, label), group in sorted(groups.items()):
        for metric in QUANTILE_METRICS:
            values = [row.get(metric) for row in group]
            rows.append({
                "scene": scene,
                "primary_label": label,
                "metric": metric,
                "mean": mean(values),
                "p10": quantile(values, 0.10),
                "p25": quantile(values, 0.25),
                "p50": quantile(values, 0.50),
                "p75": quantile(values, 0.75),
                "p90": quantile(values, 0.90),
                "num_records": len(group),
            })
    return rows


def e_reference_thresholds(parking_e_rows):
    enriched = []
    for row in parking_e_rows:
        row = dict(row)
        row.update(normalized_error_fields(row))
        enriched.append(row)
    return {
        "center_error_p75": quantile([row.get("top1_center_error") for row in enriched], 0.75),
        "size_error_norm_p75": quantile([row.get("size_l1_error_norm") for row in enriched], 0.75),
        "volume_ratio_p10": quantile([row.get("top1_volume_ratio") for row in enriched], 0.10),
        "volume_ratio_p25": quantile([row.get("top1_volume_ratio") for row in enriched], 0.25),
        "volume_ratio_p75": quantile([row.get("top1_volume_ratio") for row in enriched], 0.75),
        "volume_ratio_p90": quantile([row.get("top1_volume_ratio") for row in enriched], 0.90),
    }


def bool_value(value):
    return bool(value) if isinstance(value, bool) else False


def subtype_for(center_good, size_good, top1_iou):
    if center_good and size_good and is_finite(top1_iou) and top1_iou < 0.5:
        return (
            "center_good_size_good_but_iou_low",
            "中心和尺寸指标看起来都不差，但 IoU 仍低，可能与边界、方向、局部遮挡、相邻车辆重叠或 box 表示有关。",
        )
    if center_good and not size_good:
        return "center_good_size_bad", "中心已经比较准，但尺寸估计不准，可能需要 size refinement。"
    if not center_good and size_good:
        return "center_bad_size_good", "尺寸还可以，但中心偏移大，可能需要 center refinement。"
    return "center_bad_size_bad", "中心和尺寸都不理想，可能是目标混淆或候选质量不足。"


def make_subtype_row(row, thresholds, args):
    out = dict(row)
    out.update(normalized_error_fields(row))

    center_good_fixed = is_finite(out["top1_center_error"]) and out["top1_center_error"] <= args.center_good_abs_threshold
    size_good_fixed = is_finite(out["size_l1_error_norm"]) and out["size_l1_error_norm"] <= args.size_good_norm_threshold
    volume_good_fixed = (
        is_finite(out["top1_volume_ratio"])
        and args.volume_ratio_low <= out["top1_volume_ratio"] <= args.volume_ratio_high
    )
    center_good_ebased = (
        is_finite(out["top1_center_error"])
        and is_finite(thresholds["center_error_p75"])
        and out["top1_center_error"] <= thresholds["center_error_p75"]
    )
    size_good_ebased = (
        is_finite(out["size_l1_error_norm"])
        and is_finite(thresholds["size_error_norm_p75"])
        and out["size_l1_error_norm"] <= thresholds["size_error_norm_p75"]
    )
    volume_good_ebased = (
        is_finite(out["top1_volume_ratio"])
        and is_finite(thresholds["volume_ratio_p10"])
        and is_finite(thresholds["volume_ratio_p90"])
        and thresholds["volume_ratio_p10"] <= out["top1_volume_ratio"] <= thresholds["volume_ratio_p90"]
    )

    subtype, explanation = subtype_for(center_good_fixed, size_good_fixed, out["top1_iou"])
    out.update({
        "center_good_fixed": center_good_fixed,
        "size_good_fixed": size_good_fixed,
        "volume_good_fixed": volume_good_fixed,
        "center_good_ebased": center_good_ebased,
        "size_good_ebased": size_good_ebased,
        "volume_good_ebased": volume_good_ebased,
        "near_success": is_finite(out["top1_iou"]) and args.near_success_iou <= out["top1_iou"] < 0.5,
        "low_c": is_finite(out["top1_iou"]) and 0.25 <= out["top1_iou"] < args.low_c_iou_high,
        "center_lt_05_iou_lt_05": is_finite(out["top1_center_error"]) and out["top1_center_error"] < 0.5 and is_finite(out["top1_iou"]) and out["top1_iou"] < 0.5,
        "high_size_x_error": is_finite(out["size_x_rel_error"]) and out["size_x_rel_error"] > 0.2,
        "high_size_y_error": is_finite(out["size_y_rel_error"]) and out["size_y_rel_error"] > 0.2,
        "high_size_z_error": is_finite(out["size_z_rel_error"]) and out["size_z_rel_error"] > 0.2,
        "c_subtype": subtype,
        "subtype_explanation": explanation,
    })
    return out


def subtype_summary(rows):
    total = len(rows)
    by_subtype = defaultdict(list)
    for row in rows:
        by_subtype[row["c_subtype"]].append(row)
    output = []
    for subtype, group in sorted(by_subtype.items(), key=lambda item: (-len(item[1]), item[0])):
        output.append({
            "c_subtype": subtype,
            "count": len(group),
            "ratio": ratio(len(group), total),
            "mean_top1_iou": mean(row["top1_iou"] for row in group),
            "median_top1_iou": median(row["top1_iou"] for row in group),
            "mean_best_top10_iou": mean(row["best_top10_iou"] for row in group),
            "mean_top1_center_error": mean(row["top1_center_error"] for row in group),
            "median_top1_center_error": median(row["top1_center_error"] for row in group),
            "mean_center_error_norm": mean(row["center_error_norm"] for row in group),
            "median_center_error_norm": median(row["center_error_norm"] for row in group),
            "mean_top1_size_l1_error": mean(row["top1_size_l1_error"] for row in group),
            "median_top1_size_l1_error": median(row["top1_size_l1_error"] for row in group),
            "mean_size_l1_error_norm": mean(row["size_l1_error_norm"] for row in group),
            "median_size_l1_error_norm": median(row["size_l1_error_norm"] for row in group),
            "mean_top1_volume_ratio": mean(row["top1_volume_ratio"] for row in group),
            "median_top1_volume_ratio": median(row["top1_volume_ratio"] for row in group),
            "mean_top1_to_best_top10_iou_gap": mean(row["top1_to_best_top10_iou_gap"] for row in group),
        })
    return output


def axis_size_summary(rows):
    output = []
    for axis in ("x", "y", "z"):
        abs_values = [row[f"size_{axis}_abs_error"] for row in rows]
        rel_values = finite_values(row[f"size_{axis}_rel_error"] for row in rows)
        denom = len(rel_values)
        output.append({
            "axis": axis,
            "mean_abs_error": mean(abs_values),
            "median_abs_error": median(abs_values),
            "mean_rel_error": mean(rel_values),
            "median_rel_error": median(rel_values),
            "ratio_rel_error_gt_0.1": ratio(sum(value > 0.1 for value in rel_values), denom),
            "ratio_rel_error_gt_0.2": ratio(sum(value > 0.2 for value in rel_values), denom),
            "ratio_rel_error_gt_0.3": ratio(sum(value > 0.3 for value in rel_values), denom),
        })
    return output


def fmt(value):
    if not is_finite(value):
        return "nan"
    return f"{value:.4f}"


def metric_summary(rows, metric):
    values = [row.get(metric) for row in rows]
    return f"mean={fmt(mean(values))}, p50={fmt(median(values))}, p75={fmt(quantile(values, 0.75))}"


def findings_text(args, parking_scene, plaza_scene, parking_c, parking_e, plaza_c, plaza_e, subtype_rows, subtype_stats, axis_rows, thresholds):
    total = len(subtype_rows)
    counts = Counter(row["c_subtype"] for row in subtype_rows)
    center_lt05_count = sum(bool_value(row["center_lt_05_iou_lt_05"]) for row in subtype_rows)
    near_count = sum(bool_value(row["near_success"]) for row in subtype_rows)
    low_count = sum(bool_value(row["low_c"]) for row in subtype_rows)
    dominant_subtype = subtype_stats[0]["c_subtype"] if subtype_stats else "none"
    worst_axis = max(axis_rows, key=lambda row: safe_float(row["mean_rel_error"], -1.0))["axis"] if axis_rows else "none"

    center_problem = counts.get("center_bad_size_good", 0) + counts.get("center_bad_size_bad", 0)
    size_problem = counts.get("center_good_size_bad", 0) + counts.get("center_bad_size_bad", 0)
    both_good_low = counts.get("center_good_size_good_but_iou_low", 0)

    recommendations = []
    if ratio(size_problem, total) >= 0.4:
        recommendations.append("size 误差占比较高，BoxRefine 应优先验证 size residual，尤其关注误差最大的轴。")
    if ratio(center_problem, total) >= 0.4:
        recommendations.append("center 偏移占比较高，BoxRefine 应同时关注 center residual。")
    if ratio(both_good_low, total) >= 0.25:
        recommendations.append("不少样本 center/size 指标看起来不错但 IoU 仍低，可能需要更复杂的边界、方向、遮挡或候选机制分析。")
    if near_count > 0:
        recommendations.append("near_success 样本适合做 BoxRefine case study，因为它们距离 E 只差少量 IoU。")
    if not recommendations:
        recommendations.append("当前 subtype 未显示单一主因，建议结合可视化复核候选框和目标边界。")

    lines = [
        "parking_2 C failure detail analysis",
        "",
        f"parking2_csv: {args.parking2_csv}",
        f"plaza_csv: {args.plaza_csv}",
        f"parking_2 scene: {parking_scene}",
        f"plaza scene: {plaza_scene}",
        "",
        f"parking_2 C samples: {len(parking_c)}",
        f"parking_2 E samples: {len(parking_e)}",
        f"plaza C samples: {len(plaza_c)}",
        f"plaza E samples: {len(plaza_e)}",
        "",
        "parking_2 C vs E distribution:",
        f"  top1_iou C: {metric_summary(parking_c, 'top1_iou')}",
        f"  top1_iou E: {metric_summary(parking_e, 'top1_iou')}",
        f"  center_error C: {metric_summary(parking_c, 'top1_center_error')}",
        f"  center_error E: {metric_summary(parking_e, 'top1_center_error')}",
        f"  size_error C: {metric_summary(parking_c, 'top1_size_l1_error')}",
        f"  size_error E: {metric_summary(parking_e, 'top1_size_l1_error')}",
        f"  volume_ratio C: {metric_summary(parking_c, 'top1_volume_ratio')}",
        f"  volume_ratio E: {metric_summary(parking_e, 'top1_volume_ratio')}",
        "",
        "E-based thresholds from parking_2 E:",
        f"  center_error_p75={fmt(thresholds['center_error_p75'])}",
        f"  size_error_norm_p75={fmt(thresholds['size_error_norm_p75'])}",
        f"  volume_ratio_p10_p90=[{fmt(thresholds['volume_ratio_p10'])}, {fmt(thresholds['volume_ratio_p90'])}]",
        "",
        f"C samples with top1_center_error < 0.5: {center_lt05_count} / {total} = {fmt(ratio(center_lt05_count, total))}",
        f"near_success samples ({args.near_success_iou} <= IoU < 0.5): {near_count} / {total} = {fmt(ratio(near_count, total))}",
        f"low_c samples (0.25 <= IoU < {args.low_c_iou_high}): {low_count} / {total} = {fmt(ratio(low_count, total))}",
        "",
        "Subtype distribution:",
    ]
    for stat in subtype_stats:
        lines.append(f"  {stat['c_subtype']}: {stat['count']} / {total} = {fmt(stat['ratio'])}")
    lines.extend([
        "",
        f"Dominant subtype: {dominant_subtype}",
        f"Largest mean relative size-error axis: {worst_axis}",
        "",
        "Axis size-error summary:",
    ])
    for row in axis_rows:
        lines.append(
            f"  {row['axis']}: mean_abs={fmt(row['mean_abs_error'])}, "
            f"mean_rel={fmt(row['mean_rel_error'])}, rel>0.2={fmt(row['ratio_rel_error_gt_0.2'])}"
        )
    lines.extend([
        "",
        "Initial interpretation:",
        f"  center-related problem ratio: {fmt(ratio(center_problem, total))}",
        f"  size-related problem ratio: {fmt(ratio(size_problem, total))}",
        f"  center/size good but IoU low ratio: {fmt(ratio(both_good_low, total))}",
        "",
        "Recommendations:",
    ])
    lines.extend(f"  - {item}" for item in recommendations)
    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    parking_rows = [add_numeric_fields(row) for row in read_csv(args.parking2_csv)]
    plaza_rows = [add_numeric_fields(row) for row in read_csv(args.plaza_csv)]
    parking_scene = scene_name(parking_rows, "Outdoor_Day_penno_parking_2")
    plaza_scene = scene_name(plaza_rows, "Outdoor_Day_penno_plaza")

    groups = defaultdict(list)
    for scene, rows in ((parking_scene, parking_rows), (plaza_scene, plaza_rows)):
        for row in rows:
            if row.get("primary_label") in {C_LABEL, E_LABEL}:
                groups[(scene, row["primary_label"])].append(row)
    write_csv(out_dir / "c_error_quantiles.csv", quantile_rows(groups), QUANTILE_COLUMNS)

    parking_c = [row for row in parking_rows if row.get("primary_label") == C_LABEL]
    parking_e = [row for row in parking_rows if row.get("primary_label") == E_LABEL]
    plaza_c = [row for row in plaza_rows if row.get("primary_label") == C_LABEL]
    plaza_e = [row for row in plaza_rows if row.get("primary_label") == E_LABEL]
    thresholds = e_reference_thresholds(parking_e)

    subtype_rows = [make_subtype_row(row, thresholds, args) for row in parking_c]
    write_csv(out_dir / "parking2_c_subtype.csv", subtype_rows, SUBTYPE_COLUMNS)

    subtype_stats = subtype_summary(subtype_rows)
    write_csv(out_dir / "parking2_c_subtype_summary.csv", subtype_stats, SUBTYPE_SUMMARY_COLUMNS)

    axis_rows = axis_size_summary(subtype_rows)
    write_csv(out_dir / "parking2_c_axis_size_error_summary.csv", axis_rows, AXIS_COLUMNS)

    write_csv(
        out_dir / "parking2_c_center_lt05_cases.csv",
        [row for row in subtype_rows if bool_value(row["center_lt_05_iou_lt_05"])],
        SUBTYPE_COLUMNS,
    )
    write_csv(
        out_dir / "parking2_c_near_success_cases.csv",
        [row for row in subtype_rows if bool_value(row["near_success"])],
        SUBTYPE_COLUMNS,
    )
    write_csv(
        out_dir / "parking2_c_low_iou_cases.csv",
        [row for row in subtype_rows if bool_value(row["low_c"])],
        SUBTYPE_COLUMNS,
    )

    findings = findings_text(
        args,
        parking_scene,
        plaza_scene,
        parking_c,
        parking_e,
        plaza_c,
        plaza_e,
        subtype_rows,
        subtype_stats,
        axis_rows,
        thresholds,
    )
    (out_dir / "parking2_c_detail_findings.txt").write_text(findings, encoding="utf-8")

    files = [
        "c_error_quantiles.csv",
        "parking2_c_subtype.csv",
        "parking2_c_subtype_summary.csv",
        "parking2_c_axis_size_error_summary.csv",
        "parking2_c_center_lt05_cases.csv",
        "parking2_c_near_success_cases.csv",
        "parking2_c_low_iou_cases.csv",
        "parking2_c_detail_findings.txt",
    ]
    print(f"Saved parking2 C detail analysis to {out_dir.as_posix()}")
    print("Generated files:")
    for name in files:
        print(f"  - {name}")


if __name__ == "__main__":
    main()
